"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var bird_1 = require("./bird");
var cat_1 = require("./cat");
var cat1 = new cat_1.Cat("Garfield", "lasagna");
cat1.move(10);
var bird = new bird_1.Bird("Birdie", 12);
bird.fly(12);
cat1.eat(20);
bird.eat(10);
